# Generated by Django 4.2.11 on 2026-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255, verbose_name='Текст запроса')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Слово')),
                ('definition_data', models.JSONField(default=dict, verbose_name='Данные определения')),
                ('translation', models.TextField(blank=True, verbose_name='Перевод')),
                ('transcription', models.CharField(blank=True, max_length=50, verbose_name='Транскрипция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Определение слова',
                'verbose_name_plural': 'Определения слов',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст примера')),
                ('translated_text', models.TextField(blank=True, verbose_name='Перевод примера')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('score', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('rating', models.CharField(blank=True, max_length=50, verbose_name='Оценка')),
                ('word_count', models.IntegerField(default=0, verbose_name='Количество слов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.worddefinition', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
                'ordering': ['-score'],
            },
        ),
    ]
